services:
  db:
    image: postgres:13.22-trixie
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: helpdesk_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer:standalone
    restart: always
    ports:
      - '8081:8080'

volumes:
  pgdata:
